"""Connector platform catalog for the data-source gallery. Each tile maps to
a real underlying engine; PostgreSQL-wire and MySQL-wire platforms share
their protocol driver (the honest industry pattern — the wire protocol IS
the integration). Colors/glyphs are original, not vendor logos."""

CATALOG = [
    # --- PostgreSQL-wire family -------------------------------------------
    {"type": "postgresql", "label": "PostgreSQL", "engine": "postgresql",
     "category": "Databases", "color": "#336791", "glyph": "Pg",
     "blurb": "Connect live to any PostgreSQL 12+ database"},
    {"type": "supabase", "label": "Supabase", "engine": "postgresql",
     "category": "Databases", "color": "#3ECF8E", "glyph": "Sb",
     "blurb": "Supabase project database (PostgreSQL, SSL)"},
    {"type": "neon", "label": "Neon", "engine": "postgresql",
     "category": "Databases", "color": "#00E599", "glyph": "Ne",
     "blurb": "Neon serverless PostgreSQL (SSL required)"},
    {"type": "amazon-rds-postgresql", "label": "Amazon RDS · PostgreSQL",
     "engine": "postgresql", "category": "Databases", "color": "#FF9900",
     "glyph": "RD", "blurb": "AWS RDS / Aurora PostgreSQL endpoint"},
    {"type": "cloud-sql-postgresql", "label": "Cloud SQL · PostgreSQL",
     "engine": "postgresql", "category": "Databases", "color": "#4285F4",
     "glyph": "CS", "blurb": "Google Cloud SQL for PostgreSQL"},
    {"type": "azure-postgresql", "label": "Azure DB · PostgreSQL",
     "engine": "postgresql", "category": "Databases", "color": "#0078D4",
     "glyph": "Az", "blurb": "Azure Database for PostgreSQL flexible server"},
    {"type": "timescaledb", "label": "TimescaleDB", "engine": "postgresql",
     "category": "Databases", "color": "#FDB515", "glyph": "Ts",
     "blurb": "Timescale time-series PostgreSQL"},
    {"type": "cockroachdb", "label": "CockroachDB", "engine": "postgresql",
     "category": "Databases", "color": "#6933FF", "glyph": "Cr",
     "blurb": "CockroachDB (PostgreSQL wire protocol)"},
    # --- MySQL-wire family -------------------------------------------------
    {"type": "mysql", "label": "MySQL", "engine": "mysql",
     "category": "Databases", "color": "#00758F", "glyph": "My",
     "blurb": "Connect live to MySQL 5.7+ / 8.x"},
    {"type": "mariadb", "label": "MariaDB", "engine": "mysql",
     "category": "Databases", "color": "#C0765A", "glyph": "Ma",
     "blurb": "MariaDB server (MySQL wire protocol)"},
    {"type": "amazon-rds-mysql", "label": "Amazon RDS · MySQL",
     "engine": "mysql", "category": "Databases", "color": "#FF9900",
     "glyph": "RM", "blurb": "AWS RDS / Aurora MySQL endpoint"},
    {"type": "cloud-sql-mysql", "label": "Cloud SQL · MySQL",
     "engine": "mysql", "category": "Databases", "color": "#34A853",
     "glyph": "CM", "blurb": "Google Cloud SQL for MySQL"},
    {"type": "azure-mysql", "label": "Azure DB · MySQL", "engine": "mysql",
     "category": "Databases", "color": "#0078D4", "glyph": "AM",
     "blurb": "Azure Database for MySQL flexible server"},
    # --- SaaS applications -------------------------------------------------
    {"type": "quickbooks", "label": "QuickBooks", "engine": "quickbooks",
     "category": "SaaS apps", "color": "#2CA01C", "glyph": "QB",
     "blurb": "Invoices & balances (sandbox demo included)"},
    {"type": "hubspot", "label": "HubSpot", "engine": "hubspot",
     "category": "SaaS apps", "color": "#FF7A59", "glyph": "Hs",
     "blurb": "CRM deals & pipeline (sandbox demo included)"},
    {"type": "salesforce", "label": "Salesforce", "engine": "salesforce",
     "category": "SaaS apps", "color": "#00A1E0", "glyph": "Sf",
     "blurb": "Opportunities (sandbox demo included)"},
    {"type": "shopify", "label": "Shopify", "engine": "shopify",
     "category": "SaaS apps", "color": "#96BF48", "glyph": "Sh",
     "blurb": "Orders & revenue (sandbox demo included)"},
    {"type": "stripe", "label": "Stripe", "engine": "stripe",
     "category": "SaaS apps", "color": "#635BFF", "glyph": "St",
     "blurb": "Charges & payouts (sandbox demo included)"},
    {"type": "ga4", "label": "Google Analytics 4", "engine": "ga4",
     "category": "SaaS apps", "color": "#F9AB00", "glyph": "G4",
     "blurb": "Daily traffic & conversions (sandbox demo included)"},
    {"type": "rest-api", "label": "REST API (generic)",
     "engine": "rest-api", "category": "Business apps", "color": "#455a64",
     "glyph": "{}", "blurb": "Any read-only JSON endpoint — bring your own "
                             "API"},
    {"type": "google-sheets-csv", "label": "Google Sheets",
     "engine": "google-sheets-csv", "category": "Files & sheets",
     "color": "#0f9d58", "glyph": "▦",
     "blurb": "Publish-to-web CSV link, no OAuth"},
]

BY_TYPE = {c["type"]: c for c in CATALOG}
