"""R15: 12 industry solution packs — config, not code forks (per master
prompt §5). Each pack: KPIs, dashboard template, DQ focus, AI
recommendation seeds, connector hints. Applying a pack is honest: only
pieces whose columns exist in the target dataset are created; the rest
are reported as skipped with the reason."""

PACKS: dict[str, dict] = {
    "sales": {
        "label": "Sales & CRM",
        "kpis": [("Total revenue", "sum(amount)", "INR"),
                 ("Deals", "count()", None),
                 ("Avg deal size", "sum(amount)/count()", "INR")],
        "widgets": [("kpi", "Revenue", "sum(amount)", None),
                    ("bar", "Revenue by region", "sum(amount)", "region"),
                    ("line", "Deals over time", "count()", "stage")],
        "dq_focus": ["duplicate leads", "missing amounts"],
        "recommendations": ["Chase stale open deals",
                            "Double down on top region"],
        "connectors": ["salesforce", "hubspot", "zoho_crm_via_rest"]},
    "finance": {
        "label": "Finance & Accounting",
        "kpis": [("Cash in", "sum(amount)", "INR"),
                 ("Transactions", "count()", None)],
        "widgets": [("kpi", "Net movement", "sum(amount)", None),
                    ("waterfall", "Movement by category", "sum(amount)",
                     "category")],
        "dq_focus": ["unreconciled entries", "currency symbols in numbers"],
        "recommendations": ["Investigate negative categories",
                            "Set cash-floor alert"],
        "connectors": ["quickbooks", "xero_via_rest", "stripe"]},
    "marketing": {
        "label": "Marketing",
        "kpis": [("Spend", "sum(cost)", "INR"),
                 ("Leads", "count()", None),
                 ("Cost per lead", "sum(cost)/count()", "INR")],
        "widgets": [("kpi", "Spend", "sum(cost)", None),
                    ("funnel", "Channel funnel", "count()", "channel"),
                    ("bar", "CPL by channel", "sum(cost)/count()",
                     "channel")],
        "dq_focus": ["untagged campaigns"],
        "recommendations": ["Shift budget to lowest-CPL channel"],
        "connectors": ["ga4", "google_ads_via_rest", "meta_ads_via_rest"]},
    "retail": {
        "label": "Retail & E-commerce",
        "kpis": [("Sales", "sum(amount)", "INR"),
                 ("Orders", "count()", None),
                 ("AOV", "sum(amount)/count()", "INR")],
        "widgets": [("kpi", "Sales", "sum(amount)", None),
                    ("bar", "Sales by product", "sum(amount)", "product"),
                    ("histogram", "Order size distribution", None,
                     "amount")],
        "dq_focus": ["refund rows", "SKU typos"],
        "recommendations": ["Reorder top sellers", "Bundle slow movers"],
        "connectors": ["shopify", "stripe", "ga4"]},
    "professional_services": {
        "label": "Professional Services",
        "kpis": [("Billable value", "sum(amount)", "INR"),
                 ("Engagements", "count()", None)],
        "widgets": [("kpi", "Billables", "sum(amount)", None),
                    ("bar", "Value by client", "sum(amount)", "client"),
                    ("bar", "Hours by project", "sum(hours)", "project")],
        "dq_focus": ["missing timesheet hours"],
        "recommendations": ["Flag under-billed clients"],
        "connectors": ["quickbooks", "hubspot", "jira_via_rest"]},
    "property_management": {
        "label": "Property Management",
        "kpis": [("Rent collected", "sum(rent)", "INR"),
                 ("Units", "count()", None)],
        "widgets": [("kpi", "Rent collected", "sum(rent)", None),
                    ("bar", "Rent by property", "sum(rent)", "property"),
                    ("bar", "Arrears by tenant", "sum(balance)", "tenant")],
        "dq_focus": ["duplicate tenants", "missing lease dates"],
        "recommendations": ["Chase top arrears", "Review vacant units"],
        "connectors": ["postgres", "csv_upload"]},
    "manufacturing": {
        "label": "Manufacturing",
        "kpis": [("Output", "sum(units)", "units"),
                 ("Defects", "sum(defects)", "units"),
                 ("Defect rate", "sum(defects)/sum(units)", "%")],
        "widgets": [("kpi", "Output", "sum(units)", None),
                    ("line", "Output by line", "sum(units)", "line"),
                    ("gauge", "Defects", "sum(defects)", None)],
        "dq_focus": ["sensor gaps", "outlier readings"],
        "recommendations": ["Investigate defect spikes"],
        "connectors": ["postgres", "mysql", "rest_api"]},
    "logistics": {
        "label": "Logistics",
        "kpis": [("Shipments", "count()", None),
                 ("Freight cost", "sum(cost)", "INR")],
        "widgets": [("kpi", "Shipments", "count()", None),
                    ("bar", "Cost by route", "sum(cost)", "route"),
                    ("histogram", "Delivery days", None, "days")],
        "dq_focus": ["missing delivery timestamps"],
        "recommendations": ["Renegotiate priciest route"],
        "connectors": ["rest_api", "csv_upload"]},
    "healthcare_admin": {
        "label": "Healthcare Administration",
        "kpis": [("Appointments", "count()", None),
                 ("Billed", "sum(amount)", "INR")],
        "widgets": [("kpi", "Appointments", "count()", None),
                    ("bar", "Billed by department", "sum(amount)",
                     "department"),
                    ("bar", "No-shows by clinic", "sum(no_show)",
                     "clinic")],
        "dq_focus": ["PII classification required", "duplicate patients"],
        "recommendations": ["Reduce no-shows via reminders"],
        "connectors": ["postgres", "csv_upload"]},
    "hr": {
        "label": "Human Resources",
        "kpis": [("Headcount", "count()", None),
                 ("Payroll", "sum(salary)", "INR")],
        "widgets": [("kpi", "Headcount", "count()", None),
                    ("bar", "Headcount by department", "count()",
                     "department"),
                    ("histogram", "Tenure distribution", None,
                     "tenure_months")],
        "dq_focus": ["PII: classify salary + personal columns"],
        "recommendations": ["Review attrition-heavy departments"],
        "connectors": ["csv_upload", "rest_api"]},
    "nonprofit": {
        "label": "Nonprofit",
        "kpis": [("Donations", "sum(amount)", "INR"),
                 ("Donors", "count()", None),
                 ("Avg gift", "sum(amount)/count()", "INR")],
        "widgets": [("kpi", "Donations", "sum(amount)", None),
                    ("bar", "By campaign", "sum(amount)", "campaign"),
                    ("funnel", "Donor journey", "count()", "stage")],
        "dq_focus": ["duplicate donors"],
        "recommendations": ["Thank top donors this week"],
        "connectors": ["stripe", "mailchimp_via_rest", "csv_upload"]},
    "education": {
        "label": "Education & Training",
        "kpis": [("Enrollments", "count()", None),
                 ("Fees", "sum(fees)", "INR")],
        "widgets": [("kpi", "Enrollments", "count()", None),
                    ("bar", "By course", "count()", "course"),
                    ("histogram", "Score distribution", None, "score")],
        "dq_focus": ["missing grades"],
        "recommendations": ["Flag at-risk low scorers"],
        "connectors": ["csv_upload", "google_sheet_csv"]},
}
